/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zsim */

#ifndef _Included_zsim
#define _Included_zsim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zsim
 * Method:    roi_begin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zsim_roi_1begin
  (JNIEnv *, jclass);

/*
 * Class:     zsim
 * Method:    roi_end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zsim_roi_1end
  (JNIEnv *, jclass);

/*
 * Class:     zsim
 * Method:    heartbeat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zsim_heartbeat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
